"""Initial migration

Revision ID: 75a7baee0e98
Revises: 3e3185dae955
Create Date: 2025-06-13 20:36:32.455852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75a7baee0e98'
down_revision = '3e3185dae955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_reviews',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'review_id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('book_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'books', ['book_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    op.drop_table('book_reviews')
    # ### end Alembic commands ###
